root = "."
tmp_dir = "runtime/air"

[build]
  cmd = "go build -o gin cmd/api/main.go"
  bin = "./gin"
  delay = 1000  # ms
  exclude_dir = ["build", "runtime"]
  include_ext = ["go", "yaml"]
  kill_delay = "500ms"

[log]
  time = false
